### PR TITLE
Build: Bump dependencies

### LINKED ISSUE #22: bump in dependencies to get cats to above 1.0
I'm looking for a bump in dependencies especially on cats. I think scalajs can also be notched up to 0.6.25.

### PR DESCRIPTION
**Pull request by tindzk**
Closes #22.

### CODE REVIEW

**Comment by aappddeevv** [comment]
Did this get pushed to maven? I did not see a 0.1.2 there.

**Comment by tindzk** [comment]
Sorry for the delay! I will publish it to Maven tomorrow.

**Comment by tindzk** [comment]
@aappddeevv I just released version 0.1.2. It may take a few hours until it gets propagated.

**Comment by aappddeevv** [comment]
I see it, thanks!

**Pull request merged**
