### PR TITLE
Route: Require exact match when parsing

### LINKED ISSUE #37: Routes match more than advertised
```scala
Root.parse("/hello/world").isDefined   // true
(Root / "hello").parse("/hello/world").isDefined   // true
```

Having read the documentation, I would expect both of those to be `false`, not `true`. I don't see this behaviour explicitly tested (except indirectly [here](https://github.com/sparsetech/trail/blob/master/shared/src/test/scala/trail/RouteParseTests.scala#L23)) so I'm not sure if this is intended or not.

I don't think this is desirable behaviour:
* It makes it impossible to handle 404s – `/hello/world` is not a URL I want _any_ route to match at all
* It requires seemingly non-conflicting routes to be evaluated in a certain order – `Root / "hello"` has to go before `Root`

The only possible workaround is to append `/ ""` to the route, but that only works for `Root / ""`. In other cases it appends an undesirable "/" to the route URL, i.e. `(Root / "hello" / "").url(())` is "/hello/" instead of the desired "/hello".

I think routes should perform an exact match instead of current `startsWith`-like behaviour, and the current behaviour should be opt-in for each route using `Root / "hello" / Rest` or something like that.

---

Also unrelatedly, it appears that the linked gitter room no longer exists.

### PR DESCRIPTION
**Pull request by tindzk**
Instead of relying on route ordering, a parse should only be successful
if no path elements are left. This reverts to the behaviour pre-v0.2.0.

URLs will still parse if they contain parameters or a fragment that were
not specified in the route. However, this also can be restricted with
the newly introduced function `parseArgsStrict()`.

In cases where remaining path elements or parameters are expected, the
matchers `Elems` and `Params` were added.

Further changes include renaming of two `Route` functions:
1. `parse()` -> `parseArgs()`
2. `parseInternal()` -> `parse()`

Since these are potentially breaking changes and may require developers
to update their routing tables, the version number was increased to
v0.3.0.

Closes #37.

### CODE REVIEW

**Comment by raquo** [comment]
Nice, thanks! One comment: some third parties like to add query params to URLs for tracking ads / marketing / etc. without a way to opt-out, so you might want to reduce the strictness for query params. I guess that would make for a less consistent but a bit more practical-by-default API... not sure about this, just bringing it up in case you haven't considered this.

**Comment by tindzk** [comment]
Thanks for bringing this up! The same applies to fragments which may be set by the browser and could lead to routes not being parsed in Scala.js. I have added an additional function and reworked the public interface to reflect the new semantics. Please let me know your thoughts.

**Comment by raquo** [comment]
Looks good, thanks! You _might_ want the route itself to encode whether its query params should be parsed strictly or not (kind of like you do for path elements with `Elems`, but with the default being non-strict for params) instead of allowing the consuming library a choice of two methods for each route, but that would be more work, and I think I'd wait for someone to actually ask for that. This seems quite fine as-is to me. 👍

**Comment by tindzk** [comment]
Thanks for your feedback.

Yes, I thought about this too, but opted for the simpler approach of having multiple functions instead. Once the need arises, I'd be happy to make further changes to the interface.

**Pull request merged**
