### PR TITLE
Update Scala Native, Scalatest, Scala, Scala.js, Sbt

### LINKED ISSUE #38: Scala.js 1.0 support

### PR DESCRIPTION
**Pull request by lolgab**
Supersedes #40, closes #38 

- Use modularized Scalatest
- Update sbt-crossproject

### CODE REVIEW

**Comment by tindzk** [comment]
Thanks a lot, @lolgab. The changes look great. I will publish a new version shortly.

**Comment by lolgab** [comment]
You're welcome @tindzk 😊
I'm glad you liked the changes!
I'm writing a [Scala Native http server library](https://github.com/lolgab/snunit#routes-support) and thanks to trail supporting routes was trivial!

**Comment by tindzk** [comment]
Your library looks impressive! I will add it to the [awesome-scala-native](https://github.com/tindzk/awesome-scala-native) list.

**Comment by lolgab** [comment]
I'm happy you like it! Thanks for adding it to the list.

**Pull request merged**
